apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: prometheus-operator
  chart:
    repository: https://hub.helm.sh/charts/stable
    name: prometheus-operator
    version: 8.12.3
  values: {}
